name: Deploy React to GitHub Pages

on:
  # Запускать при пуше в ветку main
  push:
    branches: ["main"]

  # Позволяет запускать сборку вручную с вкладки Actions
  workflow_dispatch:

# Настройка прав для GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Только одна сборка одновременно
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Задача сборки (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Скачивание кода (Checkout)
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Установка зависимостей (Install)
        run: npm install
        working-directory: ./Site

      - name: Сборка проекта (Build)
        run: npm run build
        working-directory: ./Site

      - name: Подготовка артефактов (Upload artifact)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./Site/dist

  # Задача публикации (Deploy)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Публикация на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
